// Rule riêng cho mode Dữ liệu shop; registry giới hạn planner vào nguồn live/profile.
export const SHOP_DATA_PLANNER_RULE = [
    '- interactionMode=shop_data nghĩa là seller cần tra cứu dữ liệu live/hồ sơ; chỉ chọn domain kind=live-data hoặc profile trong registry và không route sang tài liệu.',
    '- shopDataIntent là phân loại ngữ nghĩa của phép đọc cần làm, không phải quyền truy cập. Với READ_QUERY trên seller-revenue, seller-orders hoặc seller-products-inventory hãy chọn đúng một intent từ enum theo toàn bộ ý câu hiện tại và ngữ cảnh đã diễn giải; không phân loại bằng khớp từ/cụm từ đơn lẻ.',
    '- seller-revenue: revenue_total là tổng doanh thu; revenue_comparison là so sánh hai kỳ; revenue_trend là xu hướng/biểu đồ theo thời gian. Câu hỏi “đơn đang giao có được tính doanh thu không” vẫn thuộc seller-revenue/revenue_total và phải giải thích theo hợp đồng: dashboard chỉ ghi nhận đơn fulfillment COMPLETED, không tính đơn SHIPPING.',
    '- seller-products-inventory: product_count đếm sản phẩm trong catalog; in_stock_product_count đếm mã sản phẩm có ít nhất một đơn vị tồn; stock_unit_count đếm tổng số đơn vị tồn; product_catalog liệt kê nhiều sản phẩm; product_detail xem một sản phẩm/biến thể cụ thể; low_stock_products là tồn thấp/cận ngưỡng (bao gồm cách nói “gần hết hàng”); out_of_stock_products chỉ là tồn bằng không; sold_products liệt kê sản phẩm có giao dịch hoàn tất trong kỳ; products_without_revenue là phần bù catalog không có doanh thu trong kỳ; top_product chọn sản phẩm bán chạy nhất; product_overview chỉ dùng khi câu hỏi chung chưa nêu metric/list/detail cụ thể và backend vẫn nạp catalog để phần trả lời/card có cùng danh sách nguồn.',
    '- seller-orders: actionable_orders là đơn còn shop cần xử lý; completed_orders đếm đơn hoàn tất; completed_order_list liệt kê đơn hoàn tất; delivered_orders liệt kê các đơn đã giao tới khách, gồm trạng thái DELIVERED và COMPLETED; cancelled_orders liệt kê đơn hủy; return_orders liệt kê đơn hoàn trả; order_status_count đếm theo trạng thái; order_detail xem thông tin đơn cụ thể; order_overview là câu hỏi chung về đơn.',
    '- Số lượng là intent đếm, không chuyển thành danh sách. Yêu cầu “thông tin của các sản phẩm này” cần product_catalog nếu referent là nhiều sản phẩm; chỉ dùng product_detail khi đang nói về một sản phẩm cụ thể. Câu nối tiếp phải giữ referent/điều kiện từ resolvedQuestion. Không được dùng product_overview thay cho yêu cầu liệt kê hoặc xem chi tiết đã nói rõ.',
    '- Với seller-profile hoặc mọi request không phải READ_QUERY ở mode khác, shopDataIntent phải là null. Các mode khác luôn để null; field này không được dùng để vượt registry/domain hay cấp quyền thực thi.',
].join(' ');
